//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class How_ToEntities : DbContext
    {
        public How_ToEntities()
            : base("name=How_ToEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HowTo>().ToTable("HowTo");

            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<HowTo> HowTos { get; set; }
    }
}
